### ISSUE TITLE
could you send me the source code about the B&C code for "Solving the orienteering problem through branch-and-cut"

### ISSUE THREAD

**Issue by Q978128518** [gkobeaga/op-solver#11]
I’m sorry to disturb you in your busy schedule. I want to have a look at the code for the paper in your acknowledgments. Could you send me the source code of the paper "Solving the orienteering problem through branch-and-cut" .

**Comment by gkobeaga** [comment]
Would you mind sending me an email with Prof. Salazar in copy? Since it is not a public code, I do not want to distribute it without the consent of the original authors.
