### ISSUE TITLE
Getting error on Make

### ISSUE THREAD

**Issue by sahilm1992** [gkobeaga/op-solver#4]
Hi I am getting the following error on doing make

```sh
make clean
../configure
make

s/libopsolver.lax/libsolver-tsp.a/lt3-libsolver_tsp_heur_la-param.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libopsolver.a
libtool: link: rm -fr .libs/libopsolver.lax
libtool: link: ( cd ".libs" && rm -f "libopsolver.la" && ln -s "../libopsolver.la" "libopsolver.la" )
gcc -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src   -g -O2 -MT op_solver-op-solver.o -MD -MP -MF .deps/op_solver-op-solver.Tpo -c -o op_solver-op-solver.o `test -f 'op-solver.c' || echo '../../src/'`op-solver.c
mv -f .deps/op_solver-op-solver.Tpo .deps/op_solver-op-solver.Po
gcc -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src   -g -O2 -MT cmd/op_solver-opt.o -MD -MP -MF cmd/.deps/op_solver-opt.Tpo -c -o cmd/op_solver-opt.o `test -f 'cmd/opt.c' || echo '../../src/'`cmd/opt.c
mv -f cmd/.deps/op_solver-opt.Tpo cmd/.deps/op_solver-opt.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o op-solver op_solver-op-solver.o cmd/op_solver-opt.o libopsolver.la -lm
libtool: link: gcc -g -O2 -o .libs/op-solver op_solver-op-solver.o cmd/op_solver-opt.o  ./.libs/libopsolver.so -lm
./.libs/libopsolver.so: undefined reference to `lp_free_solver'
./.libs/libopsolver.so: undefined reference to `lp_set_bnd'
./.libs/libopsolver.so: undefined reference to `lp_get_x'
./.libs/libopsolver.so: undefined reference to `lp_get_ncols'
./.libs/libopsolver.so: undefined reference to `cp_conv_cut_sol2connect'
./.libs/libopsolver.so: undefined reference to `cp_add_lp_cuts'
./.libs/libopsolver.so: undefined reference to `lp_opt_dual'
./.libs/libopsolver.so: undefined reference to `lp_create_solver'
./.libs/libopsolver.so: undefined reference to `cp_add_badvars'
./.libs/libopsolver.so: undefined reference to `lp_get_objval'
collect2: error: ld returned 1 exit status
Makefile:521: recipe for target 'op-solver' failed
make[3]: *** [op-solver] Error 1
```

**Comment by sahilm1992** [comment]
could you please help me

**Comment by gkobeaga** [comment]
Hi @sahilm1992, most likely it is not linking properly to the CPLEX library. Which directories do you see in `<CPLEX_PATH>/lib/`? You should see one with name `x86-64_XXX` (i.e. `x86-64_linux`).  In the following line, replace `x86-64_sles10_4.1` with your directory name:
https://github.com/gkobeaga/op-solver/blob/aa6713e1f0b79a1b39b11b304f56de53bbeb6ef9/configure.ac#L74

Then, you will need to configure and build the project again:
```sh
# To avoid problems, remove the build directory
rm -rf build
# and generate the configure file again.
./autogen.sh
mkdir -p build && cd build
# Now, continue with the ./configure part in the Readme
```
Thanks for reporting the issue. I hope this can help you.

**Comment by sahilm1992** [comment]
I had changed this, however, the error occurs even when I'm building without the cplex version.

Could you let me know the system you used + gcc version etc.

**Comment by sahilm1992** [comment]
I get the same error with cplex.

 .libs/libopsolver.lax/libsolver-tsp.a/lt3-libsolver_tsp_heur_la-param.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libopsolver.a
libtool: link: rm -fr .libs/libopsolver.lax
libtool: link: ( cd ".libs" && rm -f "libopsolver.la" && ln -s "../libopsolver.la" "libopsolver.la" )
gcc -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src   -g -O2 -MT op_solver-op-solver.o -MD -MP -MF .deps/op_solver-op-solver.Tpo -c -o op_solver-op-solver.o `test -f 'op-solver.c' || echo '../../src/'`op-solver.c
mv -f .deps/op_solver-op-solver.Tpo .deps/op_solver-op-solver.Po
gcc -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src   -g -O2 -MT cmd/op_solver-opt.o -MD -MP -MF cmd/.deps/op_solver-opt.Tpo -c -o cmd/op_solver-opt.o `test -f 'cmd/opt.c' || echo '../../src/'`cmd/opt.c
mv -f cmd/.deps/op_solver-opt.Tpo cmd/.deps/op_solver-opt.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o op-solver op_solver-op-solver.o cmd/op_solver-opt.o libopsolver.la -lm
libtool: link: gcc -g -O2 -o .libs/op-solver op_solver-op-solver.o cmd/op_solver-opt.o  ./.libs/libopsolver.so -lm
./.libs/libopsolver.so: undefined reference to `dlsym'
./.libs/libopsolver.so: undefined reference to `dlerror'
./.libs/libopsolver.so: undefined reference to `dladdr'
./.libs/libopsolver.so: undefined reference to `dlopen'
./.libs/libopsolver.so: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
Makefile:521: recipe for target 'op-solver' failed
make[3]: *** [op-solver] Error 1

**Comment by sahilm1992** [comment]
The fix solved the issue. thanks :)

**Comment by gkobeaga** [comment]
There was a problem with building the heuristic version. Thanks for reporting it. I have fixed it and add a Github Action to check the building process for the heuristic.

Anyway, building it with cplex should work. Try removing the `build` directory and configuring the project again.

**Comment by sahilm1992** [comment]
Thanks a lot

-
Sahil Manchanda
www.cse.iitd.ac.in/~sahilm
